import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import { Providers } from "./provider";
import "./globals.css";

import { Newsreader, Funnel_Sans, Playfair_Display } from "next/font/google";
import Footer from "@/components/footer";

const newsreader = Newsreader({
  subsets: ["latin"],
  variable: "--font-newsreader",
});

const funnelSans = Funnel_Sans({
  subsets: ["latin"],
  variable: "--font-funnel-sans",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-fairplay-display",
});

export const metadata: Metadata = {
  title: "Oway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${newsreader.variable} ${funnelSans.variable} ${playfairDisplay.variable}`}
      suppressHydrationWarning
    >
      <body className="mt-[76px]  ">
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
